# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x0bmap_reducer\x1a\x1bgoogle/protobuf/empty.proto\"4\n\rWORKER_STATUS\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.map_reducer.STATUS\"\x9e\x01\n\x0b\x41SSIGN_TASK\x12%\n\x07\x66\x65\x61ture\x18\x01 \x01(\x0e\x32\x14.map_reducer.FEATURE\x12!\n\x04task\x18\x02 \x01(\x0e\x32\x13.map_reducer.STATUS\x12\x12\n\ninput_file\x18\x03 \x01(\t\x12\x13\n\x0boutput_file\x18\x04 \x01(\t\x12\x1c\n\x14output_dir_files_num\x18\x05 \x01(\x03*?\n\x07\x46\x45\x41TURE\x12\x0e\n\nWORD_COUNT\x10\x00\x12\x12\n\x0eINVERTED_INDEX\x10\x01\x12\x10\n\x0cNATURAL_JOIN\x10\x02*\xd2\x01\n\x06STATUS\x12\x08\n\x04IDLE\x10\x00\x12\x11\n\rINTERIM_START\x10\x01\x12\x13\n\x0fINTERIM_WORKING\x10\x02\x12\x10\n\x0cINTERIM_DONE\x10\x03\x12\x13\n\x0fPARTITION_START\x10\x04\x12\x15\n\x11PARTITION_WORKING\x10\x05\x12\x12\n\x0ePARTITION_DONE\x10\x06\x12\x15\n\x11SUFFLE_SORT_START\x10\x07\x12\x17\n\x13SUFFLE_SORT_WORKING\x10\x08\x12\x14\n\x10SUFFLE_SORT_DONE\x10\t2\xf1\x01\n\rMapperReducer\x12I\n\x11get_worker_status\x12\x16.google.protobuf.Empty\x1a\x1a.map_reducer.WORKER_STATUS\"\x00\x12I\n\x11set_worker_status\x12\x1a.map_reducer.WORKER_STATUS\x1a\x16.google.protobuf.Empty\"\x00\x12J\n\x14\x61ssign_worker_a_task\x12\x18.map_reducer.ASSIGN_TASK\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FEATURE._serialized_start=275
  _FEATURE._serialized_end=338
  _STATUS._serialized_start=341
  _STATUS._serialized_end=551
  _WORKER_STATUS._serialized_start=60
  _WORKER_STATUS._serialized_end=112
  _ASSIGN_TASK._serialized_start=115
  _ASSIGN_TASK._serialized_end=273
  _MAPPERREDUCER._serialized_start=554
  _MAPPERREDUCER._serialized_end=795
# @@protoc_insertion_point(module_scope)
