# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import services_pb2 as services__pb2


class MapperReducerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_worker_status = channel.unary_unary(
                '/map_reducer.MapperReducer/get_worker_status',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=services__pb2.WORKER_STATUS.FromString,
                )
        self.set_worker_status = channel.unary_unary(
                '/map_reducer.MapperReducer/set_worker_status',
                request_serializer=services__pb2.WORKER_STATUS.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.assign_worker_a_task = channel.unary_unary(
                '/map_reducer.MapperReducer/assign_worker_a_task',
                request_serializer=services__pb2.ASSIGN_TASK.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class MapperReducerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_worker_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_worker_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def assign_worker_a_task(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapperReducerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_worker_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_worker_status,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=services__pb2.WORKER_STATUS.SerializeToString,
            ),
            'set_worker_status': grpc.unary_unary_rpc_method_handler(
                    servicer.set_worker_status,
                    request_deserializer=services__pb2.WORKER_STATUS.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'assign_worker_a_task': grpc.unary_unary_rpc_method_handler(
                    servicer.assign_worker_a_task,
                    request_deserializer=services__pb2.ASSIGN_TASK.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'map_reducer.MapperReducer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MapperReducer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_worker_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/map_reducer.MapperReducer/get_worker_status',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            services__pb2.WORKER_STATUS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_worker_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/map_reducer.MapperReducer/set_worker_status',
            services__pb2.WORKER_STATUS.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def assign_worker_a_task(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/map_reducer.MapperReducer/assign_worker_a_task',
            services__pb2.ASSIGN_TASK.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
